name: deploy

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12 

        with:

          region: "us"

          branch: "master"

          usedocker: true

          stack: "container"

          heroku_app_name: "emcodeing" 

          docker_heroku_process_type: worker

          heroku_email: "xdelx90@gmail.com"

          heroku_api_key: "d0a5ea07-46df-4cd8-8b7e-526ca51d30cb"
